### ISSUE TITLE
Missing mysql client package causes Drush to fail

### ISSUE THREAD

**Issue by ivanjaros** [geerlingguy/ansible-role-drush#22]
Hi,
I have just spend some time figuring out WTF when I got stuck on not being able to run drush commands when I finally realized drush requires mysql client to connect to DB and in case the DB is not local the package is not present.

Therefore I think the mysql-client package should be installed with Drush since it is basically a hard dependency.

**Comment by geerlingguy** [comment]
There are a lot of use cases, though, where the mysql client package isn't a hard requirement. In the cases where you do need it, though, I don't think it should be done as part of the `drush` role itself, rather you'd use something like `geerlingguy.php-mysql` or some other means to make sure the MySQL client package is installed.
