### ISSUE TITLE
Install directory confusion

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/ansible-role-drush#23]
Using the defaults:   

       drush_install_path: /usr/local/share/drush
       drush_path: /usr/local/bin/drush

I am getting:   
  
     Fatal error: require(): 
     Failed opening required '/var/www/drupalvm/vendor/bin/includes/preflight.inc' 
     (include_path='.:/usr/share/php') in /var/www/drupalvm/vendor/bin/drush.php on line 11

`/usr/local/share/drush/includes/preflight.inc` exists so why is drush looking in `/var/www/drupalvm/vendor/bin/includes/`?

**Comment by iainhouston** [comment]
and `which drush` gives `/usr/local/bin/drush`

**Comment by geerlingguy** [comment]
@iainhouston - When does that error occur? Does `drush status` work?

**Comment by iainhouston** [comment]
Got it! I'm installing drush twice: once with `composer create-project drupal-composer/drupal-project` and  yet again when provisioning with `drupal-vm`

The error occurred  with `drush status` before I `composer remove drush/drush`.
Now its using the `drush` as provisioned by `drupal-vm` 

All is well.

**Comment by geerlingguy** [comment]
Great! Also, see related (for Drupal VM specifically): https://github.com/geerlingguy/drupal-vm/issues/449
