### ISSUE TITLE
Git clone takes forever

### ISSUE THREAD

**Issue by TravisCarden** [geerlingguy/ansible-role-drush#27]
This role frequently takes an inordinate amount of time to complete (as in, > 20 minutes). It seems often to be hanging on the `git clone`. Could we limit the clone depth or something to make it faster? Maybe we could add a "shallow_clone" config flag or something?

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-drush/pull/10

I'll work on getting that merged now :)

**Comment by geerlingguy** [comment]
Merged! Will incorporate into Drupal VM too.

**Comment by TravisCarden** [comment]
Sweet! Thanks!
