### ISSUE TITLE
Install drush release version

### ISSUE THREAD

**Issue by joestewart** [geerlingguy/ansible-role-drush#30]
After upgrading to ansible 2.2.0.0 for DrupalVM 4.0.0, installing drush with a release version instead of a branch cannot be provisioned again.  This triggers https://github.com/ansible/ansible-modules-core/issues/5504

I'm using the following options in DrupalVM

drush_version: "8.1.8"
drush_keep_updated: true
drush_force_update: true
drush_clone_depth: 0

Using defaults other than drush_version cause issues on initial provision.

drush_version: "8.1.8"
drush_keep_updated: true ( or no)
drush_force_update: no
drush_clone_depth: 1

'FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force 8.1.8", "failed": true, "msg": "Failed to checkout 8.1.8", "rc": 1, "stderr": "error: pathspec '8.1.8' did not match any file(s) known to git.\n", "stdout": "", "stdout_lines": []}'

Is there a different combination of variables that should be used to install drush 8.1.8?

thanks

**Comment by joestewart** [comment]
It appears that changing the depth helps.  This provisioned OK.  I thought I had tested that too.

drush_version: "8.1.8"
drush_keep_updated: no
drush_force_update: no
drush_clone_depth: 0

**Comment by fubarhouse** [comment]
The `force` flag is what has previously caused that problem, so I imagine the `drush_force_update: no` is what's fixing it for you.

I've been complaining about this for some time in the ansible-core-modules repository and a fix is being rolled through, me and everybody else are simply waiting for a new release...

With that said, I've not seen the same error in some time now, maybe I should reprovision my vm...

**Comment by joestewart** [comment]
Thanks Karl, yes I learned of that bug when I ran into it with one of your roles then found you had commented on the core module issue.

In some circumstances the composer install step was being skipped too so the last step to run drush to finish setup failed.

**Comment by wizonesolutions** [comment]
I notice that 8.x installs the dev version. Can we get an option to `--prefer-stable` (assuming we are still using Composer to install)? I'd expect 8.1.8, but I would like new versions without having to update my playbook.

**Comment by geerlingguy** [comment]
@wizonesolutions - Currently there's only the possibility of installing a specific tag, or a branch. And `8.x` will chase HEAD on that branch, whereas a specific tag (e.g. `8.1.8`) will lock in that tag. Unfortunately, there isn't a way to tell Ansible "choose the most recent tag in a certain branch" since it's all git refs and there's no formal association between tags and branches.

**Comment by wizonesolutions** [comment]
Yeah. Is there a particular reason we prefer Git? I wonder if there are alternatives that would behave like Composer. Or maybe just a simple option that installs the latest stable as per http://www.drush.org/en/master/install/ instead of using GIt? Anyway, I came in here due to an unrelated issue I was having and that wasn't Drush at all...and so I don't actually currently feel strongly about this anyway :)

**Comment by geerlingguy** [comment]
@wizonesolutions - I definitely wouldn't be opposed to defaulting to a `.phar` download (if we can get that running smoothly and securely). Very few people need the actual git clone—it's just the only way that was reliable for all systems back when I set up the foundation for this role in 2012 or 2013 :)

**Comment by back-2-95** [comment]
Phar could be good solution if the smooth and securely can be satisfied. Now the `Install Drush dependencies with Composer.` task might be the slowest task there is.

**Comment by geerlingguy** [comment]
@back-2-95 - And technically, you could bypass that entirely if you use a drush makefile to download a tagged Drupal release (which would include the dependencies).

**Comment by wizonesolutions** [comment]
I'm back here again, haha. This is happening with...whatever we are doing with Composer, etc.

FIRST PASS:

```
fatal: [default]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:00.250811", "end": "2017-02-23 23:12:38.873263", "failed": true, "rc": 2, "start": "2017-02-23 23:12:38.622452", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for phpunit/phpunit 4.8.31 -> satisfiable by phpunit/phpunit[4.8.31].\n    - phpunit/phpunit 4.8.31 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n\n  To enable extensions, verify that they are enabled in your .ini files:\n    - /etc/php/7.1/cli/php.ini\n    - /etc/php/7.1/cli/conf.d/10-opcache.ini\n    - /etc/php/7.1/cli/conf.d/10-pdo.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu_bc.ini\n    - /etc/php/7.1/cli/conf.d/20-calendar.ini\n    - /etc/php/7.1/cli/conf.d/20-ctype.ini\n    - /etc/php/7.1/cli/conf.d/20-exif.ini\n    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.1/cli/conf.d/20-ftp.ini\n    - /etc/php/7.1/cli/conf.d/20-gettext.ini\n    - /etc/php/7.1/cli/conf.d/20-iconv.ini\n    - /etc/php/7.1/cli/conf.d/20-json.ini\n    - /etc/php/7.1/cli/conf.d/20-phar.ini\n    - /etc/php/7.1/cli/conf.d/20-posix.ini\n    - /etc/php/7.1/cli/conf.d/20-readline.ini\n    - /etc/php/7.1/cli/conf.d/20-shmop.ini\n    - /etc/php/7.1/cli/conf.d/20-sockets.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}
```

SUBSEQUENT PASSES:

```
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.132101", "end": "2017-02-23 23:15:31.010603", "failed": true, "rc": 1, "start": "2017-02-23 23:15:30.878502", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has dependencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}
```

I had the thought to run the Drush role as a normal user, but actually, then the `drush_path` wouldn't work.

This issue seemed somewhat relevant https://github.com/composer/composer/issues/5749, but whether it applies to me and what to do if it does was unclear. Will keep banging on this.

**Comment by wizonesolutions** [comment]
I moved it to the subsequent play and somehow that might've worked. Have to test it with a clean build still but it's probably Somehow Me™

**Comment by geerlingguy** [comment]
Working on this in a dev branch.

**Comment by geerlingguy** [comment]
Nice little speedup:

  - Phar-based install: ~02:30s
  - Git-based install: ~03:10s

Nothing groundbreaking, but it also avoids running Composer too.

I can also ditch the hard requirements on the other roles now and just suggest them for the rest of the build.

**Comment by back-2-95** [comment]
Nice one, thanks!
