### ISSUE TITLE
Switching between source and no-source fails.

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-drush#34]
Before 2.0 the default was to do a git clone & composer install.
This creates `{{ drush_path }}` as a symbolic link.
This fails if it already exists as a file.

The new default is to download a phar.
This creates `{{ drush_path }}` as a file with `get_url`.
This fails with a "src and dest are required for creating links" error if it alredy exists as a link.

So I see two issues:
- running 2.0 on a system provisioned with an older version will fail.
- switching between `drush_install_from_source: yes` and `drush_install_from_source: no` will fail.

Bug encountered with ansible 2.2.1.0

**Comment by geerlingguy** [comment]
@JorisVanEijden - True... for the projects where I'm using this role, I rebuild the VMs/servers frequently, so haven't run into this. But a few devs have noted the behavior, and the workarounds currently are:

  - Stick with the source install until you rebuild the server.
  - Rebuild the server now.

But the PR looks sane, so I'll merge and get into Drupal VM's next release. Thanks!
