### ISSUE TITLE
Slightly misleading info in README re: `drush_version` variable

### ISSUE THREAD

**Issue by ctorgalson** [geerlingguy/ansible-role-drush#36]
## Description

The permissible values for the `drush_version` variable vary according to the value of `drush_install_from_source`. 

If ([as in the default case](https://github.com/geerlingguy/ansible-role-drush/blob/master/defaults/main.yml#L8)) that value is set to `no`, the contents of `drush_version` are [used to create the `drush_phar_url` variable](https://github.com/geerlingguy/ansible-role-drush/blob/master/defaults/main.yml#L4).

However, the only mention of `drush_version` in the README comes under the heading [Variables used for source install (Git)](https://github.com/geerlingguy/ansible-role-drush/blob/master/README.md#variables-used-for-source-install-git) where it says

> The version of Drush to install (examples: "master" for the bleeding edge, "7.x", "6.x", "6.2.0"). This should be a string as it refers to a git branch, tag, or commit hash.

But in the default case, `drupal_version` can only be a release, not a tag, branch, etc. This causes playbooks using values such as `8.x` to fail since `https://github.com/drush-ops/drush/releases/download/8.x/drush.phar` does not exist.

## Suggested resolution

1. Add `drush_version` to "Role Variables" section indicating only releases can be used.
2. Modify `drush_version` description in "Variables used for source install (Git)" section to explain that tags, branches, and commit hashes can also be used.

**Comment by ctorgalson** [comment]
Created PR #37 with documentation suggestions.

**Comment by geerlingguy** [comment]
@ctorgalson - Thanks! merged https://github.com/geerlingguy/ansible-role-drush/pull/37
