### ISSUE TITLE
Post install permissions issue

### ISSUE THREAD

**Issue by Synchro** [geerlingguy/ansible-role-drush#38]
Hi Guy,

I have umask set to a very strict 077, and while this role sets permissions for drush itself correctly, it doesn't set it for the commands, so I end up with:

```
user@server:/var/www/mysite/webroot$ sudo ls -al /usr/share/drush/commands                                                      
total 32
drwx--x--x 8 root root 4096 Jul 30 13:51 .
drwx--x--x 8 root root 4096 Jul 30 13:51 ..
drwx--x--x 3 root root 4096 Jul 30 13:51 core
drwx--x--x 2 root root 4096 Jul 30 13:51 make
drwx--x--x 6 root root 4096 Jul 30 13:51 pm
drwx--x--x 2 root root 4096 Jul 30 13:51 runserver
drwx--x--x 2 root root 4096 Jul 30 13:51 sql
drwx--x--x 2 root root 4096 Jul 30 13:51 user
```

I'm guessing you're applying `+x` to these; it could do with `+r` as well.

**Comment by geerlingguy** [comment]
I'm assuming you mean the task here https://github.com/geerlingguy/ansible-role-drush/blob/master/tasks/install.yml#L21 — I would be willing to accept a PR to do something similar for all the tasks inside the commands directory as well, but I don't have the time to add/test it myself right now (most of my servers aren't quite as strict!).

**Comment by Synchro** [comment]
I'm looking into doing that. I installed with `drush_install_from_source: no` and `drush_path: /usr/local/bin/drush`, and drush was installed in `/usr/local/bin/drush` as expected, but the commands were put in `/usr/share/drush/commands` instead of `/usr/local/share/drush/commands` even though I set `drush_install_path: /usr/local/share/drush`.

I can see that `drush_install_path` is only used during source installs, and evidently isn't used for a non-source install - so how can I reliably figure out where drush commands will be placed (so I can fix their permissions) without making platform-dependent assumptions?
