### ISSUE TITLE
Getting Internal Server Error for 2.0.1.tar.gz

### ISSUE THREAD

**Issue by uniquename** [geerlingguy/ansible-role-drush#39]
When I try to download 
https://github.com/geerlingguy/ansible-role-drush/archive/2.0.1.tar.gz
I'm getting a 500. 

Is that a github issue or is there something to be fixed?

**Comment by joestewart** [comment]
https://status.github.com/

August 23, 2017

07:40 CDTWe're investigating reports of problems fetching raw and release content.
07:31 CDTWe are investigating reports of elevated error rates.

**Comment by uniquename** [comment]
Thanks for the quick answer. I'll close this issue.
