### ISSUE TITLE
Unable to update drush

### ISSUE THREAD

**Issue by pminf** [geerlingguy/ansible-role-drush#43]
Hey, I've already reported this issue in the drupal-vm repo (https://github.com/geerlingguy/drupal-vm/issues/1594) but according to @thom8 it seems to be an ansible role issue.

### Issue Type

Bug Report

### Environment

Drupal-VM 4.7.0
Vagrant 1.9.6
VirtualBox 5.1.28 r117968 (Qt5.6.2)

### OS

Microsoft Windows 10 Pro (Version 10.0.14393 Build 14393)

### Full console output

config.yml
```
drush_version: "8.1.14"
```

```
vagrant reload --provision
[...]
TASK [geerlingguy.drush : Check current state.] ********************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Perform cleanup of old symlink.] *********************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Install Drush.] **************************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Ensure Drush is executable.] *************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Clone Drush from GitHub.] ****************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Check for composer.json] *****************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Ensure Drush can be installed on Debian Wheezy.] *****
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Create drush symlink.] *******************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
skipping: [mydrupalvm]

[...]

TASK [Configure host machine drush aliases.] ***********************************
changed: [mydrupalvm -> 127.0.0.1]

TASK [Ensure drush directory exists for vagrant user inside VM.] ***************
ok: [mydrupalvm]

TASK [Configure drush aliases for vagrant user inside VM.] *********************
changed: [mydrupalvm]

TASK [Ensure drush directory exists for root user inside VM.] ******************
ok: [mydrupalvm]

TASK [Configure drush aliases for root user inside VM.] ************************
ok: [mydrupalvm]

[...]
mydrupalvm       : ok=202  changed=2    unreachable=0    failed=0
```

```
vagrant@drupal:/var/www$ drush version
 Drush Version   :  8.1.10
```

### Summary

Although if have set up the vm to use Drush 8.1.14 the current version is still 8.1.10. Of course I've updated my vm via `vagrant reload --provision`. I had to destroy the vm and install again to use 8.1.14.

Both options `drush_keep_updated: yes` and `drush_force_update: yes` don't resolve this.

It might related to Drupal-VM update 4.3.1 (2017-03-14), because of

> * Removed now-unneccessary `drush_keep_updated`

**Comment by joestewart** [comment]
```- name: Install Drush.
  get_url:
    url: "{{ drush_phar_url }}"
    dest: "{{ drush_path }}"```

Looks like since drush_path exists for re-provisions the get_url doesn't replace the existing installation.

**Comment by thom8** [comment]
Ahh yep that will be it.

I'm using `drush_install_from_source: yes` which bypasses this task which is why I couldn't replicate it.

**Comment by geerlingguy** [comment]
@pminf - Unless you're using `drush_install_from_source: yes`, this feature won't do anything at the current time. It's recommended you use Composer to manage Drush per-project now, and this role's been radically altered to work with Drush Launcher by default instead of a global Drush install anyways.
