### ISSUE TITLE
document conflict in variables

### ISSUE THREAD

**Issue by John-B** [geerlingguy/ansible-role-drush#48]
Document the fact that if drush_composer_global_install is set to 'yes', drush_launcher_install must be 'no', otherwise the role bails out with 
 FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "refusing to convert between file and link for /usr/local/bin/drush", "owner": "root", "path": "/usr/local/bin/drush", "size": 274420, "state": "file", "uid": 0}

**Comment by benjifisher** [comment]
It looks as though this has already been fixed. Under [Drush global install via Composer](https://github.com/geerlingguy/ansible-role-drush#drush-global-install-via-composer) in this repo's main README, it says,

> `drush_composer_global_install: false`
> 
> Set to `yes` (and set `drush_launcher_install` to `false`) if you want to install `drush` globally using Composer.

**Comment by geerlingguy** [comment]
Yep, thanks for noticing @benjifisher !
