### ISSUE TITLE
cannot change to directory '/usr/local/share/drush': path does not exist

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/ansible-role-drush#5]
Just tried using this role but get this error every time (I'm even using your Composer role too).

```
TASK: [geerlingguy.drush | Install Drush dependencies with Composer.] ********* 
failed: [178.62.17.8] => {"failed": true, "rc": 258}
msg: cannot change to directory '/usr/local/share/drush': path does not exist
```

**Comment by geerlingguy** [comment]
You'll need to set `drush_keep_updated: yes` for now, until the next version of Ansible is released; there was a bug with the way the git module works that prevents it from cloning the repository when that's set to `no` :(

**Comment by danbohea** [comment]
Thanks. That's stopped the error.
