### ISSUE TITLE
Fails on "Install Drush dependencies with Composer." with drush5

### ISSUE THREAD

**Issue by ba66e77** [geerlingguy/ansible-role-drush#7]
I may be the only one who cares, but worth noting at least that the "Install Drush dependencies with Composer." step fails with Drush 5 (and presumably lower) since they do not include a composer.json file.

**Comment by geerlingguy** [comment]
D'oh! I guess I haven't installed that old a version of Drush in quite a while.

I think the simplest way to fix this is to add a variable, `drush_composer_install`, defaulted to `true`, and then add a line in the documentation stating that this controls whether or not Composer will be used to complete installation, and that Drush < 6 should have this set to `false`.

**Comment by thom8** [comment]
Rather than adding another var we should only run ```composer install``` when composer.json exists.
