### ISSUE TITLE
Not a git repository error from "Clone Drush from GitHub" task.

### ISSUE THREAD

**Issue by dkinzer** [geerlingguy/ansible-role-drush#9]
I'm getting the following error when I try to use this role from within a `packer push...` build on Atlas.

![screen shot 2015-08-09 at 7 48 56 am](https://cloud.githubusercontent.com/assets/444215/9156411/43a6148a-3ea7-11e5-9863-b083f786945b.png)

I can't figure out why this is happening, and I'm not certain it's a bug with your role or not, but I thought I report it just in case.

**Comment by dkinzer** [comment]
OK, I'm closing this because it looks like this may be do to the fact that I am using submodules and not related to your role at all:
kelseyhightower/packer-provisioner-ansible-local#2

**Comment by brackindustries** [comment]
@dkinzer, we are using submodules, too... And get the same error. Could you point to more info on what problems arise from using submodules?

Regards
